services:

    #handbrake adapter service
    transcoding.adapter.handbrake:
        class: AC\Transcoding\Adapter\HandbrakeAdapter
        arguments: [%ac_transcoding.handbrake.path%, %ac_transcoding.handbrake.timeout%]
        tags:
            - {name: transcoding.adapter}

    #handbrake preset services
    transcoding.preset.handbrake.apple_tv2:
        class: AC\Transcoding\Preset\Handbrake\AppleTV2Preset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.apple_tv_legacy:
        class: AC\Transcoding\Preset\Handbrake\AppleTVLegacyPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.apple_tv:
        class: AC\Transcoding\Preset\Handbrake\AppleTVPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.classic:
        class: AC\Transcoding\Preset\Handbrake\ClassicPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.high_profile:
        class: AC\Transcoding\Preset\Handbrake\HighProfilePreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.ipad:
        class: AC\Transcoding\Preset\Handbrake\iPadPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.iphone4:
        class: AC\Transcoding\Preset\Handbrake\iPhone4Preset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.iphone_ipod_touch:
        class: AC\Transcoding\Preset\Handbrake\iPhoneiPodTouchPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.iphone_legacy:
        class: AC\Transcoding\Preset\Handbrake\iPhoneLegacyPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.ipod_legacy:
        class: AC\Transcoding\Preset\Handbrake\iPodLegacyPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.ipod:
        class: AC\Transcoding\Preset\Handbrake\iPodPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.normal:
        class: AC\Transcoding\Preset\Handbrake\NormalPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.universal:
        class: AC\Transcoding\Preset\Handbrake\UniversalPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}
