parameters:
    transcoding.handbrake.class: AC\Component\Transcoding\Adapter\HandbrakeAdapter
    
    #path to handbrake executable on filesystem
    transcoding.handbrake.path: /usr/local/bin/HandBrakeCLI

    #how long handbrake commands should run before timeout, null means no timeout
    transcoding.handbrake.timeout: null

services:
    
    #handbrake adapter service
    transcoding.adapter.handbrake:
        class: %transcoding.handbrake.class%
        arguments: [%transcoding.handbrake.path%, %transcoding.handbrake.timeout%]
        tags:
            - {name: transcoding.adapter}

    #handbrake preset services
    transcoding.preset.handbrake.apple_tv2:
        class: AC\Component\Transcoding\Preset\Handbrake\AppleTV2Preset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.apple_tv_legacy:
        class: AC\Component\Transcoding\Preset\Handbrake\AppleTVLegacyPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.apple_tv:
        class: AC\Component\Transcoding\Preset\Handbrake\AppleTVPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.classic:
        class: AC\Component\Transcoding\Preset\Handbrake\ClassicPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.high_profile:
        class: AC\Component\Transcoding\Preset\Handbrake\HighProfilePreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.ipad:
        class: AC\Component\Transcoding\Preset\Handbrake\iPadPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.iphone4:
        class: AC\Component\Transcoding\Preset\Handbrake\iPhone4Preset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.iphone_ipod_touch:
        class: AC\Component\Transcoding\Preset\Handbrake\iPhoneiPodTouchPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.iphone_legacy:
        class: AC\Component\Transcoding\Preset\Handbrake\iPhoneLegacyPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.ipod_legacy:
        class: AC\Component\Transcoding\Preset\Handbrake\iPodLegacyPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.ipod:
        class: AC\Component\Transcoding\Preset\Handbrake\iPodPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.normal:
        class: AC\Component\Transcoding\Preset\Handbrake\NormalPreset
        tags:
            - {name: transcoding.preset}

    transcoding.preset.handbrake.universal:
        class: AC\Component\Transcoding\Preset\Handbrake\UniversalPreset
        tags:
            - {name: transcoding.preset}
