services:

    #ffmpeg adapter service
    transcoding.adapter.ffmpeg:
        class: AC\Transcoding\Adapter\FFmpegAdapter
        arguments: [%ac_transcoding.ffmpeg.path%, %ac_transcoding.ffmpeg.timeout%]
        tags:
            - {name: transcoding.adapter}


    #ffmpeg preset services
    transcoding.preset.ffmpeg.avi_to_animated_gif:
        class: AC\Transcoding\Preset\FFmpeg\AviToAnimatedGifPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.ffmpeg.convert_non_m_video:
        class: AC\Transcoding\Preset\FFmpeg\ConvertNonMVideoPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}

    transcoding.preset.ffmpeg.sound_from_video:
        class: AC\Transcoding\Preset\FFmpeg\SoundFromVideoPreset
        scope: prototype
        tags:
            - {name: transcoding.preset}
