# Core service is just the transcoder service.
# Compiler passes register any adapters/presets/listeners via container tags
parameters:
    transcoder.class: AC\Component\Transcoding\Transcoder

services:
    transcoder:
        class: %transcoder.class%
        arguments: [@event_dispatcher]
